# Generated by Django 5.2.5 on 2025-08-26 11:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('gaming', 'Игровой'), ('workstation', 'Рабочая станция'), ('office', 'Офисный'), ('home', 'Домашний')], max_length=20, verbose_name='Категория')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('processor', models.CharField(max_length=255, verbose_name='Процессор')),
                ('graphics_card', models.CharField(max_length=255, verbose_name='Видеокарта')),
                ('ram', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('storage', models.CharField(max_length=255, verbose_name='Накопитель')),
                ('power_supply', models.CharField(max_length=100, verbose_name='Блок питания')),
                ('case', models.CharField(max_length=255, verbose_name='Корпус')),
                ('cooling', models.CharField(max_length=255, verbose_name='Охлаждение')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Операционная система')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComputerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='computers/%Y/%m/%d/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'Изображение компьютера',
                'verbose_name_plural': 'Изображения компьютеров',
                'ordering': ['order'],
            },
        ),
    ]
