# Generated by Django 5.2.5 on 2025-08-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('working', 'В работе'), ('finish', 'Готов к выдаче')], default='waiting', max_length=20, verbose_name='Статусы'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tag',
            field=models.CharField(choices=[('waiting details', 'Ожидание деталей'), ('deliver', 'В доставке'), ('trouble', 'Проблема'), ('close', 'Закрыт')], default='waiting details', max_length=20, verbose_name='Тэги'),
        ),
    ]
