# Generated by Django 5.2.5 on 2025-08-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequest', '0002_servicerequest_status_servicerequest_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код тега')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='tag',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('working', 'В работе'), ('finish', 'Готов к выдаче')], default='waiting', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите один или несколько тегов', to='ServiceRequest.tag', verbose_name='Теги'),
        ),
    ]
