# Generated by Django 5.2.5 on 2025-08-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequest', '0003_tag_remove_servicerequest_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#333333', help_text='Выберите цвет в формате HEX, например: #007bff', max_length=7, verbose_name='Цвет тега'),
        ),
    ]
